apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faculties-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" # Reemplazar por 'gce' para usar el controlador de Ingress de Google en lugar de NGINX.
spec:
  ingressClassName: nginx # Reemplazar por 'gce' para asegurar la compatibilidad con el Ingress de Google en GCE.
  rules:
    - http:
        paths:
          - path: /agronomy
            pathType: Prefix
            backend:
              service:
                name: agronomy-faculty-service
                port:
                  number: 80
          - path: /engineering
            pathType: Prefix
            backend:
              service:
                name: engineering-faculty-service
                port:
                  number: 80
