apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faculties-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  rules:
    - host: olympics.local # Remover cuando se despliegue en GKE, ya que no se configurará el DNS.
      http:
        paths:
          - path: /agronomy
            pathType: Prefix
            backend:
              service:
                name: agronomy-faculty-service
                port:
                  number: 80
          - path: /engineering
            pathType: Prefix
            backend:
              service:
                name: engineering-faculty-service
                port:
                  number: 80
