apiVersion: v1
kind: Service
metadata:
  name: agronomy-faculty-service
  labels:
    app: agronomy-faculty
spec:
  selector:
    app: agronomy-faculty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
