{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Información del Clúster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodos del Clúster",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "kube_node_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Pods del Clúster",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "kube_pod_info{namespace=~\"default|kafka\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Conectores del Clúster",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kube_endpoint_info{namespace=~\"default|kafka\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Servicios del Clúster",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "kube_service_info{namespace=~\"default|kafka\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Utilización de Recursos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latencia al Percentil 95 de Agronomía",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{endpoint=\"/agronomy\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latencia al Percentil 95 de Ingeniería",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{endpoint=\"/engineering\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cantidad de Solicitudes HTTP",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_requests_total{endpoint=\"/agronomy\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "http_requests_total{endpoint=\"/engineering\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Rendimiento de las Facultades",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uso de la CPU en los Últimos 5 Minutos",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uso de Memoria",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_Active_bytes / node_memory_MemTotal_bytes) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uso de Disco",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "    (\n        node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}\n      -\n        node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"}\n    )\n  /\n    node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}\n*\n  100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}