apiVersion: networking.k8s.io/v1 # Esta es la versión de la API para el recurso Ingress. En este caso, estamos usando la versión estable.
kind: Ingress # Esto especifica que el recurso que se está creando es un Ingress.
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: nginx.local # El host al que se asignará el Ingress.
      http:
        paths:
          - path: / # Coincide con solicitudes a la raíz del dominio.
            pathType: Prefix # Coincide con cualquier solicitud que comience con '/'.
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
