apiVersion: kafka.strimzi.io/v1beta2 # Versión de la API de Strimzi que usamos para manejar Kafka.
kind: KafkaTopic
metadata:
  name: olympics-results
  labels:
    strimzi.io/cluster: kafka-cluster
  namespace: kafka
spec:
  partitions: 3
  replicas: 3
