apiVersion: kafka.strimzi.io/v1beta2 # Versión de la API de Strimzi que usamos para manejar Kafka.
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.8.0 # Versión de Kafka que queremos instalar.
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal # El listener es "internal", lo que significa que solo es accesible dentro del cluster de Kubernetes.
        tls: false # No se habilita TLS para este listener. TLS es un protocolo que encripta datos para comunicaciones seguras.
    storage:
      type: ephemeral
  zookeeper: # Configuración de Zookeeper, necesario para la coordinación de Kafka.
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: { } # Operador para gestionar automáticamente los topics de Kafka.
    userOperator: { } # Operador para gestionar automáticamente los usuarios de Kafka.
