apiVersion: kafka.strimzi.io/v1beta2 # Versión de la API de Strimzi que usamos para manejar Kafka.
kind: KafkaTopic
metadata:
  name: olympics-losers
  labels:
    strimzi.io/cluster: kafka-cluster
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
