apiVersion: v1
kind: Service
metadata:
  name: agronomy-faculty-service
  labels:
    app: agronomy-faculty
  annotations:
    cloud.google.com/healthcheck-path: "/agronomy/healthz" # Ruta que Google Cloud usará para verificar la salud del servicio.
    cloud.google.com/neg: '{"ingress": true}' # Configura el uso de un Network Endpoint Group para optimizar el tráfico a través del Ingress.
spec:
  type: ClusterIP
  selector:
    app: agronomy-faculty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
