apiVersion: v1
kind: Service
metadata:
  name: disciplines-service
  labels:
    app: disciplines
spec:
  type: ClusterIP
  selector:
    app: disciplines
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
