apiVersion: v1
kind: Service
metadata:
  name: engineering-faculty-service
  labels:
    app: engineering-faculty
spec:
  selector:
    app: engineering-faculty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
