apiVersion: v1
kind: Service
metadata:
  name: swimming-competition-service
  labels:
    app: swimming-competition
spec:
  selector:
    app: swimming-competition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
