[package]
name = "rust-service"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
ctrlc = "3.2"
log = "0.4"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.12.2"
