apiVersion: apps/v1
kind: Deployment
metadata:
  name: agronomy-faculty-deployment
  labels:
    app: agronomy-faculty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agronomy-faculty
  template:
    metadata:
      labels:
        app: agronomy-faculty
    spec:
      containers:
        - name: agronomy-faculty-container
          image: agronomy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
