apiVersion: apps/v1
kind: Deployment
metadata:
  name: agronomy-faculty-deployment
  labels:
    app: agronomy-faculty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agronomy-faculty
  template:
    metadata:
      labels:
        app: agronomy-faculty
    spec:
      containers:
        - name: agronomy-faculty-container
          image: agronomy:latest # Remplazar a 'gcr.io/<PROJECT-ID>/agronomy:latest' para que Kubernetes en GKE pueda acceder a la imagen.
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe: # Verifica si la aplicación está lista para recibir tráfico.
            httpGet:
              path: /agronomy/healthz # Si la respuesta es exitosa, el pod es marcado como listo para recibir tráfico.
              port: 8080
            initialDelaySeconds: 30 # Espera 30 segundos antes de realizar la primera verificación.
            periodSeconds: 10 # Realiza la verificación cada 10 segundos.
          livenessProbe:
            httpGet:
              path: /agronomy/healthz # Si la respuesta es exitosa, el pod es marcado como saludable.
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
