apiVersion: apps/v1
kind: Deployment
metadata:
  name: disciplines-deployment
  labels:
    app: disciplines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disciplines
  template:
    metadata:
      labels:
        app: disciplines
    spec:
      containers:
        - name: disciplines-container
          image: disciplines:latest # Remplazar a 'gcr.io/<PROJECT_ID>/disciplines:latest' para que Kubernetes en GKE pueda acceder a la imagen.
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
