apiVersion: apps/v1
kind: Deployment
metadata:
  name: disciplines-deployment
  labels:
    app: disciplines
spec:
  replicas: 3
  selector:
    matchLabels:
      app: disciplines
  template:
    metadata:
      labels:
        app: disciplines
    spec:
      containers:
        - name: disciplines-container
          image: disciplines:latest # Remplazar a 'gcr.io/<PROJECT-ID>/disciplines:latest' para que Kubernetes en GKE pueda acceder a la imagen.
          imagePullPolicy: Never # Reemplazar a 'Always' en GKE para garantizar que Kubernetes descargue la imagen más reciente en cada despliegue.
          ports:
            - containerPort: 8080
